// Code generated by mockery v2.32.0. DO NOT EDIT.

package apn

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockbadTokensSavingRepo is an autogenerated mock type for the badTokensSavingRepo type
type MockbadTokensSavingRepo struct {
	mock.Mock
}

type MockbadTokensSavingRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockbadTokensSavingRepo) EXPECT() *MockbadTokensSavingRepo_Expecter {
	return &MockbadTokensSavingRepo_Expecter{mock: &_m.Mock}
}

// addBadToken provides a mock function with given fields: ctx, token
func (_m *MockbadTokensSavingRepo) addBadToken(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockbadTokensSavingRepo_addBadToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'addBadToken'
type MockbadTokensSavingRepo_addBadToken_Call struct {
	*mock.Call
}

// addBadToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockbadTokensSavingRepo_Expecter) addBadToken(ctx interface{}, token interface{}) *MockbadTokensSavingRepo_addBadToken_Call {
	return &MockbadTokensSavingRepo_addBadToken_Call{Call: _e.mock.On("addBadToken", ctx, token)}
}

func (_c *MockbadTokensSavingRepo_addBadToken_Call) Run(run func(ctx context.Context, token string)) *MockbadTokensSavingRepo_addBadToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockbadTokensSavingRepo_addBadToken_Call) Return(_a0 error) *MockbadTokensSavingRepo_addBadToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockbadTokensSavingRepo_addBadToken_Call) RunAndReturn(run func(context.Context, string) error) *MockbadTokensSavingRepo_addBadToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockbadTokensSavingRepo creates a new instance of MockbadTokensSavingRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockbadTokensSavingRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockbadTokensSavingRepo {
	mock := &MockbadTokensSavingRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
