name: Print info in Slack

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  slackinfo:
    name: SlackInfo
    runs-on: ubuntu-20.04
    steps:
      - name: Get the current date and time
        id: date
        run: echo "current_date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: Send custom JSON data to Slack workflow
        id: slack
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "*GitHub Actions: New build* ${{ steps.date.outputs.date }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*GitHub Actions: New build* ${{ env.current_date }}\n\n*URL:* ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK