name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      SQL_AUTHENTICATION_INIT_FILE_PATH: ${{ github.workspace }}/build/id/postgresql/init.sql
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Run tests
        run: go test -coverprofile=coverage.out ./...
      - name: Set job result message
        id: set_result
        if: always()
        run: |
          if [[ "${{ job.status }}" == "success" ]]; then
            echo "result_message=:hugging_face: Success" >> $GITHUB_ENV
          else
            echo "result_message=:hushed: Failure" >> $GITHUB_ENV
          fi
      - name: Send custom JSON data to Slack workflow
        id: slack
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Workflow *${{ github.workflow }}* - Result: *${{ job.status }}*",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Workflow:* ${{ github.workflow }}\n*Result:* ${{ env.result_message }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK